Adding narrative_config.yaml spec
kbase/index_runner pull request #196
Opened 2021-01-25 23:04 UTC by slebras

* [ ] I incremented the version in the `VERSION` file
* [ ] I updated `CHANGELOG.md`
* [ ] I added test coverage for any changes

2021-01-25 23:17 UTC, scanon requested changes

2021-01-25 23:17 UTC, scanon commented on spec/narrative_config.yaml
> +    - narrative_1
Let's drop narrative_1 since it can lead to duplicate hits.

2021-02-17 19:21 UTC, scanon commented
@slebras Can you redo this PR?

2021-02-17 22:30 UTC, jayrbolton approved these changes
Looks good. Just needs merge conflict with CHANGELOG.md resolved

2021-02-18 21:16 UTC, merged